// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keycloak owns the "public" schema — app tables live in "app" schema
    url: (process.env["DATABASE_URL"] ?? "") + "?schema=app",
  },
});
